config/routes.rb
# frozen_string_literal: true

Smartvpn::Application.routes.draw do
  require 'sidekiq/web'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  namespace :billing do
    root to: 'home#index'

    resources :payments, only: %i[index new create] do
      member do
        get :merchant
      end
    end
    resources :promotions, only: [:create]
    resources :options, only: %i[index create update destroy] do
      put :toggle, on: :member
    end
    resources :referrers, only: [:index]
    resources :servers, only: [:index] do
      get :download_config, on: :member
    end

    scope '/webmoney' do
      get 'fail', to: 'webmoney#fail', as: :webmoney_fail
      get 'success', to: 'webmoney#success', as: :webmoney_success
      match 'result', to: 'webmoney#result', as: :webmoney_result, via: %i[get post]
    end

    scope '/robokassa' do
      get 'fail', to: 'robokassa#fail', as: :robokassa_fail
      get 'success', to: 'robokassa#success', as: :robokassa_success
      post 'result', to: 'robokassa#result', as: :robokassa_result
    end

    scope '/paypal' do
      get 'fail', to: 'paypal#fail', as: :paypal_fail
      get 'success', to: 'paypal#success', as: :paypal_success
      match 'result', to: 'paypal#result', as: :paypal_result, via: %i[get post]
    end
  end

  namespace :admin do
    root to: 'home#index'
    resources :servers do
      get :generate_config, on: :member
    end
    resources :plans
    resource :profile, only: %i[edit update]
    resources :pay_systems, except: :destroy
    resources :users, except: :destroy do
      collection do
        get :payers
        get :this_month_payers
        get :emails_export
      end
      member do
        put :withdraw
        put :prolongate
        put :payment
        put :enable_test_period
        put :disable_test_period
        put :force_disconnect
      end
    end
    resources :connections, only: %i[index show] do
      get :active, on: :collection
    end
    resources :traffic_reports, only: [:index] do
      collection do
        get :users
        get :date
        get :servers
      end
    end
    resources :transactions, only: [:index] do
      collection do
        get :payments
        get :withdrawals
      end
    end
    resources :promos, only: %i[index new create edit update]
    resources :options, only: %i[index new create edit update]
    resources :referrers, only: [:index]
    resource :change_languages, only: :update
  end

  namespace :api do
    match '/activate', to: 'servers#activate', via: [:post]
    match '/auth', to: 'authentication#auth', via: [:post]
    match '/disconnect', to: 'connection#disconnect', via: [:post]
    match '/connect', to: 'connection#connect', via: [:post]
  end

  match '/referrer', to: 'referrers#set_referrer', via: [:get]
  root to: 'main#index'

  authenticate :admin do
    mount Sidekiq::Web, at: '/sidekiq'
    mount PgHero::Engine, at: 'pghero'
  end
end

app/models/pay_system.rb
# frozen_string_literal: true

class PaySystem < ActiveRecord::Base
  include AASM

  CURRENCIES = %w[usd rub eur].freeze

  has_many :payments
  validates :name, :code, presence: true
  scope :enabled, -> { where(state: :enabled) }

  aasm column: :state do
    state :disabled, initial: true
    state :enabled

    event :enable do
      transitions from: :disabled, to: :enabled
    end

    event :disable do
      transitions from: :enabled, to: :disabled
    end
  end
end

# == Schema Information
#
# Table name: pay_systems
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  code        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  description :text
#  state       :string(255)
#  currency    :string(255)      default("usd")
#

app/controllers/admin/pay_systems_controller.rb
# frozen_string_literal: true

class Admin::PaySystemsController < Admin::BaseController
  before_action :load_resource, only: %i[show edit update destroy]

  def index
    @pay_systems = PaySystem.all.decorate
  end

  def show; end

  def new
    @pay_system = PaySystem.new
  end

  def create
    @pay_system = PaySystem.new(resource_params)
    if @pay_system.save
      redirect_to admin_pay_systems_path, notice: 'Платежная система успешно добавлена'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @pay_system.update(resource_params)
      redirect_to admin_pay_systems_path, notice: 'Платежная система успешно обновлена'
    else
      render :edit
    end
  end

  private

  def load_resource
    @pay_system = PaySystem.find(params[:id])
  end

  def resource_params
    params.require(:pay_system).permit(:name, :code, :description, :state, :currency)
  end
end

app/views/admin/pay_systems/_form.html.slim
.row
  .col.mt-5
    = simple_form_for [:admin, @pay_system], html: { class: 'form-horizontal' },wrapper: :horizontal_form do |f|
      = f.input :name
      = f.input :code
      = f.input :description
      = f.input :state,
        as: :select,
        collection: PaySystem.aasm.states.map { |s| [t("admin.pay_systems.states.#{s.name}"), s.name] },
        include_blank: false
      = f.input :currency, as: :select, collection: PaySystem::CURRENCIES.map { |c| [c, c] }
      br
      = f.submit t('admin.buttons.apply'), class: 'btn btn-primary'

app/views/admin/pay_systems/edit.html.slim
= page_title(t('admin.pay_systems.title'), 'server', 'pay_systems') do
  = sub_page_title("#{t('admin.pay_systems.edit')} #{@pay_system.name}")

= render partial: 'form'

app/views/admin/pay_systems/index.html.slim
= page_title(t('admin.pay_systems.title'), 'server', 'pay_systems')

.row.my-4
  .col
    = link_to t('admin.links.create'), new_admin_pay_system_path, class: 'btn btn-primary'

table.table
  thead
    tr
      th= t('admin.tables.id')
      th= t('admin.tables.name')
      th= t('admin.tables.code')
      th= t('admin.tables.state')
      th= t('admin.tables.actions')

  tbody
    - @pay_systems.each do |pay_system|
      tr
        td= pay_system.id
        td= pay_system.title
        td= pay_system.code
        td= pay_system.human_state
        th
          = link_to t('admin.links.edit'), edit_admin_pay_system_path(pay_system), class: 'btn btn-sm btn-info'

app/views/admin/pay_systems/new.html.slim
= page_title(t('admin.pay_systems.title'), 'server', 'pay_systems') do
  = sub_page_title(t('admin.pay_systems.new'))

= render partial: 'form'

app/views/admin/pay_systems/show.html.slim
= page_title(t('admin.pay_systems.title'), 'user', 'pay_systems') do
  = sub_page_title("#{t('admin.pay_systems.show')} #{@pay_system.name}")

.my-3
  = link_to t('admin.links.edit'), edit_admin_pay_system_path(@pay_system), class: 'btn btn-sm btn-info'

= show_for @pay_system do |pay_system|
  = pay_system.attribute :id
  = pay_system.attribute :name
  = pay_system.attribute :code
  = pay_system.attribute :description
  = pay_system.attribute :state